blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/markgorzynski/color-utils/discussions
    about: Please ask and answer questions in GitHub Discussions
  - name: Security Issues
    url: https://github.com/markgorzynski/color-utils/security/policy
    about: Please report security vulnerabilities via the security policy